[package]
name = "fox"
version = "0.1.0"
edition = "2021"
description = "Terminal-based code editor with syntax highlighting"
license = "GPL-3.0-only"

[dependencies]
crossterm = "0.25.0"
clap = "3.2.17"
owo-colors = "3.4.0"

# Syntax highlighting
syntect = "4.6"
carbon-dump = "1.2.2"
